name: Node.js Testing Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint server.js server.test.js

      - name: Run Jest tests
        run: npm test

      - name: Run UI tests (Selenium)
        run: |
          # Start server in background for UI tests
          node server.js &
          SERVER_PID=$!
          sleep 5
          
          # Test server is responding
          curl -f http://localhost:3000/health || { echo "Server failed to start"; kill $SERVER_PID; exit 1; }
          
          # Run the UI tests with local Selenium (if Chrome is available)
          timeout 300 node ui-tests.js || echo "UI tests completed or timed out"
          
          # Clean up
          kill $SERVER_PID
        continue-on-error: true
